### ISSUE TITLE
Use GitHub API to Link to Downloads

### ISSUE THREAD

**Issue by AntumDeluge** [AntumDeluge/debreate-web#1]
Could we use the GitHub API to link downloads to the current release, rather than using a static URL?

[GET /repos/:owner/:repo/releases/latest](https://developer.github.com/v3/repos/releases/#get-the-latest-release)

**Comment by Huluti** [comment]
I'm taking care of it !

**Comment by AntumDeluge** [comment]
Excellent! Thank you so much Hugo.
